<a href="https://colab.research.google.com/github/zoobe125/20230205-Python/blob/main/20230219.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Q：＂%＂怎麼使用？

參考：

嘗試執行底下程式,按按鈕A觀察結果！


```
# # Imports go at the top
from microbit import *

display.clear()

x = 0
y = 0
display.set_pixel(x,y,9)

while True:
    if button_a.was_pressed():
        x = x+1
        display.clear()
        display.set_pixel(x%5,y,9)
```



In [1]:
6%5

1

In [2]:
7%5

2

###複習request使用

從政府資料開放平台抓資料:
https://data.gov.tw/

###練習

抓取＂年度國內主要金融指標＂作分析

https://apiservice.mol.gov.tw/OdService/download/A17000000J-030244-dpp

In [12]:
import requests

In [18]:
url = "https://apiservice.mol.gov.tw/OdService/download/A17000000J-030244-dpp"

In [19]:
data = requests.get(url).json()

In [20]:
#列出data內的清單
data

[{'年度': '1994',
  '貨幣供給額期底年增率-M1B': '12.23',
  '貨幣供給額期底年增率-M2': '15.07',
  '金價（美元／英兩）-國際現貨黃金價格': '382.50',
  '金價（美元／英兩）-台北': '385.07',
  '匯率（月底）-（新台幣／美元）': '26.240',
  '外匯存底（億美元）': '924.54',
  '利率（年息%）-金融業拆款': '6.130',
  '利率（年息%）-商業本票31-90天期': '6.77',
  '利率（年息%）-中央銀行重貼現率': '5.500',
  '利率（年息%）-債券市場（十年期中央政府公債）': '7.24',
  '證券（集中市場）-發行量加權股價指數（月底）': '7124.66',
  '證券（集中市場）-成交值（億元）': '194766'},
 {'年度': '1995',
  '貨幣供給額期底年增率-M1B': '0.76',
  '貨幣供給額期底年增率-M2': '9.42',
  '金價（美元／英兩）-國際現貨黃金價格': '386.65',
  '金價（美元／英兩）-台北': '388.51',
  '匯率（月底）-（新台幣／美元）': '27.265',
  '外匯存底（億美元）': '903.10',
  '利率（年息%）-金融業拆款': '6.191',
  '利率（年息%）-商業本票31-90天期': '6.68',
  '利率（年息%）-中央銀行重貼現率': '5.500',
  '利率（年息%）-債券市場（十年期中央政府公債）': '6.79',
  '證券（集中市場）-發行量加權股價指數（月底）': '5173.73',
  '證券（集中市場）-成交值（億元）': '103052'},
 {'年度': '1996',
  '貨幣供給額期底年增率-M1B': '8.31',
  '貨幣供給額期底年增率-M2': '9.13',
  '金價（美元／英兩）-國際現貨黃金價格': '369.30',
  '金價（美元／英兩）-台北': '368.08',
  '匯率（月底）-（新台幣／美元）': '27.491',
  '外匯存底（億美元）': '880.38',
  '利率（年息%）-金融業拆款': '5.439',
 

In [21]:
#檢視data的資料型態
type(data)


list

In [22]:
#檢視data有幾筆資料
len(data)

29

In [24]:
#data內第一筆資料
data[0]

{'年度': '1994',
 '貨幣供給額期底年增率-M1B': '12.23',
 '貨幣供給額期底年增率-M2': '15.07',
 '金價（美元／英兩）-國際現貨黃金價格': '382.50',
 '金價（美元／英兩）-台北': '385.07',
 '匯率（月底）-（新台幣／美元）': '26.240',
 '外匯存底（億美元）': '924.54',
 '利率（年息%）-金融業拆款': '6.130',
 '利率（年息%）-商業本票31-90天期': '6.77',
 '利率（年息%）-中央銀行重貼現率': '5.500',
 '利率（年息%）-債券市場（十年期中央政府公債）': '7.24',
 '證券（集中市場）-發行量加權股價指數（月底）': '7124.66',
 '證券（集中市場）-成交值（億元）': '194766'}

###列出各年度貨幣供給額

####方法一

In [26]:
#方法一 i:變數從data內取出
for i in data:
  print(i['年度'],"==>",i['貨幣供給額期底年增率-M2'])

1994 ==> 15.07
1995 ==> 9.42
1996 ==> 9.13
1997 ==> 8.02
1998 ==> 8.56
1999 ==> 8.29
2000 ==> 6.50
2001 ==> 4.31
2002 ==> 2.53
2003 ==> 5.68
2004 ==> 7.19
2005 ==> 6.63
2006 ==> 5.15
2007 ==> 0.84
2008 ==> 7.21
2009 ==> 5.78
2010 ==> 5.44
2011 ==> 4.84
2012 ==> 3.46
2013 ==> 5.79
2014 ==> 6.13
2015 ==> 5.80
2016 ==> 3.55
2017 ==> 3.56
2018 ==> 2.65
2019 ==> 4.52
2020 ==> 9.36
2021 ==> 7.35
2022 ==> 6.74


####方法二

In [29]:
for i in range(len(data)):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28


In [33]:
#方法二
for i in range(len(data)):
  print(data[i]['年度'],"==>" ,data[i]['貨幣供給額期底年增率-M2'])

1994 ==> 15.07
1995 ==> 9.42
1996 ==> 9.13
1997 ==> 8.02
1998 ==> 8.56
1999 ==> 8.29
2000 ==> 6.50
2001 ==> 4.31
2002 ==> 2.53
2003 ==> 5.68
2004 ==> 7.19
2005 ==> 6.63
2006 ==> 5.15
2007 ==> 0.84
2008 ==> 7.21
2009 ==> 5.78
2010 ==> 5.44
2011 ==> 4.84
2012 ==> 3.46
2013 ==> 5.79
2014 ==> 6.13
2015 ==> 5.80
2016 ==> 3.55
2017 ==> 3.56
2018 ==> 2.65
2019 ==> 4.52
2020 ==> 9.36
2021 ==> 7.35
2022 ==> 6.74


##資料分析基礎套件

---

* numpy (科學運算基礎套件)
* matplotlib (繪圖基礎套件)
* pandas (資料分析基礎套件)




### 套件載入的慣用法

---


```
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```






## NumPy

### NumPy ==> **Num**erical **Py**thon


* ndarray (多維陣列) ==> N-Dimensional Array
* ufunc (通用函式) ==> Universal Functions

In [34]:
import numpy as np

### ndarray

#### 原生的python容器型別限制
無法簡單做出簡單的科學運算(向量計算)！

In [35]:
x = [1, 2, 3]
y = [4, 5, 6]

In [36]:
x + y

[1, 2, 3, 4, 5, 6]

In [37]:
2 * x

[1, 2, 3, 1, 2, 3]

#### 使用numpy的ndarray來解決科學運算問題

In [38]:
x1 = np.array(x)
y1 = np.array(y)

In [39]:
type(x1)

numpy.ndarray

In [40]:
x1

array([1, 2, 3])

In [41]:
y1

array([4, 5, 6])

In [42]:
x1 + y1

array([5, 7, 9])

In [43]:
2 * x1

array([2, 4, 6])

### ufunc

#### 原生的python的數學運算

In [44]:
import math

In [45]:
math.pi

3.141592653589793

In [48]:
math.sin(math.pi/2)

1.0

In [49]:
math.sin(x)

TypeError: ignored

#### 比較一下NumPy的使用

In [50]:
np.pi

3.141592653589793

In [51]:
np.sin(np.pi/2)

1.0

In [52]:
np.sin(x1)

array([0.84147098, 0.90929743, 0.14112001])